max_width = 100
tab_spaces = 4
newline_style = "unix"          # f*** windows style
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true

# they seem to be stable in nearest future, but for now we use it only for nightly CI check
unstable_features = true
normalize_comments = true
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
wrap_comments = true
